
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-access-smi-spec-io-v1alpha4-identitybinding
  failurePolicy: Fail
  name: videntitybinding.kb.io
  rules:
  - apiGroups:
    - access.smi-spec.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - identitybindings
  sideEffects: None
