# permissions for end users to edit identitybindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: identitybinding-editor-role
rules:
- apiGroups:
  - access.smi-spec.io
  resources:
  - identitybindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - access.smi-spec.io
  resources:
  - identitybindings/status
  verbs:
  - get
