# permissions for end users to view identitybindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: identitybinding-viewer-role
rules:
- apiGroups:
  - access.smi-spec.io
  resources:
  - identitybindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - access.smi-spec.io
  resources:
  - identitybindings/status
  verbs:
  - get
