# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/split.smi-spec.io_trafficsplits.yaml
- bases/specs.smi-spec.io_httproutegroups.yaml
- bases/specs.smi-spec.io_tcproutes.yaml
- bases/specs.smi-spec.io_udproutes.yaml
- bases/access.smi-spec.io_traffictargets.yaml
- bases/access.smi-spec.io_identitybindings.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
- patches/webhook_in_trafficsplits.yaml
- patches/webhook_in_httproutegroups.yaml
- patches/webhook_in_tcproutes.yaml
- patches/webhook_in_udproutes.yaml
- patches/webhook_in_traffictargets.yaml
- patches/webhook_in_identitybindings.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
- patches/cainjection_in_trafficsplits.yaml
- patches/cainjection_in_httproutegroups.yaml
- patches/cainjection_in_tcproutes.yaml
- patches/cainjection_in_udproutes.yaml
- patches/cainjection_in_traffictargets.yaml
- patches/cainjection_in_identitybindings.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
